# Corre todos los tests del módulo con output verbose
test:
	go test ./... -v

# Compila el binario y lo pone en bin/
build:
	go build -o bin/costhandler_agent ./cmd/server

# Compila y ejecuta
run:
	go run ./cmd/server

# Limpia binarios generados
clean:
	rm -rf bin/

